chromatic/chromatic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chromatic_app.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chromatic/chromatic_app/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

urlpatterns = [
    path('', views.home, name='chromatic_app_home'),
    path('register/', views.register, name='chromatic_app_register'),
    path('login/', LoginView.as_view(template_name='chromatic_app/login.html'), name='chromatic_app_login'),
    path('logout/', LogoutView.as_view(template_name='chromatic_app/logout.html'), name='chromatic_app_logout'),
    path('upload/', views.upload, name='chromatic_app_upload'),
]

chromatic/chromatic_app/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
    image = models.ImageField(null=False, blank=False)
    annotatedImage = models.ImageField(null=True, blank=True)
    uploader = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    caption = models.CharField(max_length=400, null=False, blank=False)
    public = models.BooleanField(default=True)
    upload_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.caption

class Face(models.Model):
    post = models.ForeignKey(Post, null=False, on_delete=models.CASCADE)
    topLeftX = models.IntegerField(null=False)
    topLeftY = models.IntegerField(null=False)
    width = models.IntegerField(null=False)
    height = models.IntegerField(null=False)

    def __str__(self):
        return f'{self.post.pk}-({self.topLeftX}, {self.topLeftY})'

chromatic/chromatic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

chromatic/chromatic_app/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.conf import settings

from .forms import UserRegisterForm
from .models import Post, Face
from .utils import get_faces

def home(request):
    context = {
        'posts': Post.objects.all(),
    }
    return render(request, 'chromatic_app/home.html', context)

def login(request):
    return render(request, 'chromatic_app/login.html')

def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}!')

            return redirect('chromatic_app_login')
    else:
        form = UserRegisterForm()

    context = {
        'form' : form,
    }

    return render(request, 'chromatic_app/register.html', context)

@login_required(login_url='chromatic_app_login')
def upload(request):
    if request.method == 'POST':
        caption = request.POST.get('caption', '')
        image = request.FILES.get('imagefile')

        post = Post(
            uploader=request.user,
            caption=caption,
            image=image,
        )
        post.save()

        faces = get_faces(str(image))
        for (x, y, w, h) in faces:
            face = Face(
                post=post,
                topLeftX=x,
                topLeftY=y,
                width=w,
                height=h,
            )
            face.save()

        return redirect('chromatic_app_home')

    return render(request, 'chromatic_app/upload_image.html')

chromatic/chromatic_app/templates/chromatic_app/home.html
{% load static %}
{% load humanize %}
<!DOCTYPE html>
<html lang="en">
    <head>
        {% include "chromatic_app/includes/head.html" %}
        <link rel="stylesheet" type="text/css" href="{% static 'chromatic_app/css/navbar.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'chromatic_app/css/global_styles.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'chromatic_app/css/home.css' %}">
        <title>Chromatic Home Page</title>
    </head>
    <body>
        {% include "chromatic_app/includes/navbar.html" %}
        {% include "chromatic_app/includes/messages.html" %}
        <div class="container mainContainer">
            <div class="row">
                <div class="col-md-10">
                    <h2>Explore stories from around the world</h2>
                    <div class="cardsContainer">
                        {% for post in posts %}
                            <div class="card cardMain" onclick="showImageModal('imageModal{{ post.id }}')">
                                <img class="card-img-top cardImage" src="{{ post.image.url }}" />
                                <div class="card-body cardBody">
                                    <div class="cardUserContainer">
                                        <div class="cardAvatarContainer">
                                            <img class="cardAvatar" alt="avatar" src="https://avatars.dicebear.com/api/jdenticon/{{ post.uploader.id }}.svg" />
                                        </div>
                                        <div class="cardTextContainer">
                                            <h6 class="card-title">{{ post.uploader.get_username }}</h6>
                                            <h6 class="card-subtitle mb-2 text-muted cardSubtitle">{{ post.upload_date|naturaltime }}</h6>
                                        </div>
                                    </div>
                                    <p class="card-text cardText"><i>{{ post.caption }}</i></p>
                                </div>
                            </div>
                            <div class="modal fade" id="imageModal{{ post.id }}" tabindex="-1" role="dialog" aria-labelledby="imageModal{{ post.id }}" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="imageModalHeading{{ post.id }}">Facial Recognition</h5>
                                            <button type="button" class="close" style="border: none; border-radius: 15px;" data-dismiss="modal" aria-label="Close" onclick="hideImageModal('imageModal{{ post.id }}')">
                                            <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body imageModalBody">
                                            <img id="imageModalImg" alt="" src="{{ post.image.url }}" />
                                            {% for face in post.face_set.all %}
                                                <div class="box" style="top: {{ face.topLeftY }}%; left: {{ face.topLeftX }}%; width: {{ face.width }}%; height: {{ face.height }}%;"></div>
                                            {% endfor %}
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal" onclick="hideImageModal('imageModal{{ post.id }}')">Close</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% empty %}
                            <p><br />Oops! Nothing here yet! :(</p>
                        {% endfor %}
                    </div>
                </div>
                <div class="col-md-2">
                    {% include "chromatic_app/includes/afghanistan_donation.html" %}
                </div>
            </div>
        </div>
        <script>
            function showImageModal(modalName) {
                $('#' + modalName).modal('show');
            }

            function hideImageModal(modalName) {
                $('#' + modalName).modal('hide');
            }
        </script>
        {% include "chromatic_app/includes/scripts.html" %}
    </body>
</html>

chromatic/chromatic_app/templates/chromatic_app/includes/afghanistan_donation.html
<button
    class="special-button"
    onclick="window.open('https://www.islamicreliefcanada.org/emergencies/afghanistan-emergency/', '_blank').focus();">
    Donate to Afghanistan
</button>

chromatic/chromatic_app/templates/chromatic_app/includes/head.html
{% load static %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'chromatic_app/css/global_styles.css' %}">

chromatic/chromatic_app/templates/chromatic_app/includes/messages.html
{% if messages %}
    {% for message in messages %}
        <div class = "alert alert-{{ message.tags }}">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

chromatic/chromatic_app/templates/chromatic_app/includes/navbar.html
{% load static %}
<nav class="navbar navbar-expand-md navbar-light bg-light navbar-bg">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">
            <img alt="Chromatic logo" src="{% static 'chromatic_app/img/chromatic_logo.png' %}" width="70" />
        </a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link navbarTextLink" id="navbarStuff" href="/">Home</a>
                </li>
            </ul>
            {% if user.is_authenticated %}
                <a class="nav-item nav-link navbarTextLink" id="navbarStuff" href="{% url 'chromatic_app_upload' %}">Upload Image +</a>
                <a class="nav-item nav-link navbarTextLink" id="navbarStuff" href="{% url 'chromatic_app_logout' %}">Logout</a>
            {% else %}
                <a class="nav-item nav-link navbarTextLink" id="navbarStuff" href="{% url 'chromatic_app_login' %}">Login</a>
                <a class="nav-item nav-link navbarTextLink" id="navbarStuff" href="{% url 'chromatic_app_register' %}">Register</a>
            {% endif %}
        </div>
    </div>
</nav>

chromatic/chromatic_app/templates/chromatic_app/includes/scripts.html
<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>

chromatic/chromatic_app/templates/chromatic_app/login.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html>
    <head>
        {% include "chromatic_app/includes/head.html" %}
        <link rel="stylesheet" type="text/css" href="{% static 'chromatic_app/css/navbar.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'chromatic_app/css/global_styles.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'chromatic_app/css/login.css' %}">
        <title>Login</title>
    </head>
    <body>
        {% include "chromatic_app/includes/navbar.html" %}
        {% include "chromatic_app/includes/messages.html" %}
        <div class="container mainContainer">
            <div class="row">
                <div class="col-md-10">
                    <div class="form-content">
                        <form method="POST">
                            {% csrf_token %}
                            <fieldset class="form-group">
                                <legend class="border-bottom mb-4">Log in to your account</legend>
                                {{ form|crispy }}
                            </fieldset>
                            <div class="form-group">
                                <button class="special-button" type="submit">Login</button>
                            </div>
                        </form>
                        <div class="border-top pt-3">
                            <small class="text-muted">
                                Don't have an account? <a class="ml-2" href="{% url 'chromatic_app_register' %}"> Sign Up</a>
                            </small>
                        </div>
                    </div>
                </div>
                <div class="col-md-2">
                    {% include "chromatic_app/includes/afghanistan_donation.html" %}
                </div>
            </div>
        </div>
            {% include "chromatic_app/includes/scripts.html" %}
    </body>
</html>

chromatic/chromatic_app/templates/chromatic_app/logout.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        {% include "chromatic_app/includes/head.html" %}
        <link rel="stylesheet" type="text/css" href="{% static 'chromatic_app/css/navbar.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'chromatic_app/css/global_styles.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'chromatic_app/css/logout.css' %}">
        <title>Logout</title>
    </head>
    <body>
        {% include "chromatic_app/includes/navbar.html" %}
        {% include "chromatic_app/includes/messages.html" %}
        <div class="container mainContainer">
            <div class="row">
                <div class="col-md-10">
                    <div class="form-content">
                        <h1 class="display-5">You have been logged out.</h1>
                        <div class="border-top pt-3">
                            <small class="text-muted">
                                <a class="ml-2" href="{% url 'chromatic_app_login' %}">Log In Again</a>
                            </small>
                        </div>
                    </div>
                </div>
                <div class="col-md-20">
                    {% include "chromatic_app/includes/afghanistan_donation.html" %}
                </div>
            </div>
        </div>
        {% include "chromatic_app/includes/scripts.html" %}
    </body>
</html>

chromatic/chromatic_app/templates/chromatic_app/register.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
    <head>
        {% include "chromatic_app/includes/head.html" %}
        <link rel="stylesheet" type="text/css" href="{% static 'chromatic_app/css/navbar.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'chromatic_app/css/global_styles.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'chromatic_app/css/register.css' %}">
        <title>Register</title>
    </head>
<body>
    {% include "chromatic_app/includes/navbar.html" %}
    {% include "chromatic_app/includes/messages.html" %}
    <div class="container mainContainer">
        <div class="row">
            <div class="col-md-10">
                <div class="form-content">
                    <form method="POST">
                        {% csrf_token %}
                        <fieldset class="form-group">
                            <legend class="border-bottom mb-4">Register for an account</legend>
                            {{ form|crispy }}
                        </fieldset>
                        <div class="form-group">
                            <button class="special-button" type="submit">Register</button>
                        </div>
                    </form>
                    <div class = "border-top pt-3">
                        <small class = "text-muted">
                            Already have an account? <a class="ml-2" href="{% url 'chromatic_app_login' %}">Login</a>
                        </small>
                    </div>
                </div>
            </div>
            <div class="col-md-2">
                {% include "chromatic_app/includes/afghanistan_donation.html" %}
            </div>
        </div>
    </div>
</body>
</html>

chromatic/chromatic_app/templates/chromatic_app/upload_image.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        {% include "chromatic_app/includes/head.html" %}
        <link rel="stylesheet" type="text/css" href="{% static 'chromatic_app/css/navbar.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'chromatic_app/css/global_styles.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'chromatic_app/css/upload_image.css' %}">
        <title>Chromatic Home Page</title>
    </head>
    <body>
        {% include "chromatic_app/includes/navbar.html" %}
        {% include "chromatic_app/includes/messages.html" %}
        <div class="container mainContainer">
            <div class="row">
                <div class="col-md-10">
                    <form method="POST" action="" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group m-3">
                            <label>Caption</label>
                            <input name="caption" type="text" class="form-control" placeholder="Enter a caption for the image" required />
                        </div>
                        <div class="form-group m-3">
                            <label>Choose image file</label>
                            <input name="imagefile" type="file" class="form-control-file" required />
                        </div>
                        <div class="form-group">
                            <button class="special-button" type="submit">Upload</button>
                        </div>
                    </form>
                </div>
                <div class="col-md-2">
                    {% include "chromatic_app/includes/afghanistan_donation.html" %}
                </div>
            </div>
        </div>
        <script>
            function showImageModal(src) {
                $('#imageModal').modal('show');
                $('#imageModalImg').attr('src', src);
            }

            function hideImageModal() {
                $('#imageModal').modal('hide');
            }
        </script>
        {% include "chromatic_app/includes/scripts.html" %}
    </body>
</html>